name: Update README

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Update README with recent activity
        uses: jamesgeorge007/github-activity-readme@master
        with:
          GH_USERNAME: czarekmilek
          COMMIT_MSG: ":zap: Update README with recent activity"
          MAX_LINES: 5
          TARGET_FILE: README.md
          INCLUDE: "PushEvent"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}